name: bsdoc pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Esy
        run: |
          npm install -g esy@0.6.2
      - name: Install Esy deps
        run: |
          esy install

      - name: Print Esy cache
        id: print-esy-cache
        run: node .github/workflows/scripts/print-esy-cache.js
      - name: Restore Esy cache
        id: esy-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.print-esy-cache.outputs.esy-cache }}
          key: ${{ matrix.os }}-esy-${{ hashFiles('**/index.json') }}

      - name: Build
        run: |
          esy build
      - name: Test
        run: |
          esy test
      - name: Release
        run: |
          esy release
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: _release

  rc:
    needs: build
    name: Prepare RC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Download Linux artifacts
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-latest
          path: linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v1
        with:
          name: macOS-latest
          path: darwin

      - name: Download Windows artifacts
        uses: actions/download-artifact@v1
        with:
          name: windows-latest
          path: windows

      - name: Move artifacts
        run: |
          mkdir -p _release/platforms
          mv linux _release/platforms/linux-x64
          mv darwin _release/platforms/darwin-x64
          mv windows _release/platforms/win-x64
      - name: Move files
        run: |
          cp .github/workflows/scripts/postinstall.js _release/postinstall.js
          cp LICENSE _release/
          cp README.md _release/
          node .github/workflows/scripts/write-package-json.js
      - name: Upload release
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: _release
